#------------- Rocket parameters --------------------
#
# Defines parameters specific to the Control algorithm:
#   - General dimensions of the components
#   - Rocket engine specifications
#   - Targeted apogee
#
# ----------------------------------------------------
Q:
  - 500     # position
  - 500
  - 0.0
  - 1000.0 # speed
  - 1000.0
  - 0.0
  - 0.0    # quaternion
  - 0.0
  - 0.0
  - 0.0
  - 0      # angular rate
  - 0
  - 0
  - 0.0    # mass
theta: 1.0e+4
R:
  - 1
  - 1
  - 10
  - 0
