#------------- Rocket parameters --------------------
#
# Defines parameters specific to the rocket:
#   - General dimensions of the components
#   - Rocket engine specifications
#   - Targeted apogee
#
# ----------------------------------------------------
stages: 4
diameters:
  - 0
  - 0.156 
  - 0.156 
  - 0.135
stage_z:
  - 0 
  - 0.242 
  - 3.43 
  - 3.51 
fin_n: 4
fin_top_offset: 3.15 
fin_span: 0.17 # 0.05
fin_root_chord: 0.28 # base length
fin_tip_chord: 0.125
fin_sweep: 0.107
fin_thickness: 0.004
lug_n: 2
lug_S: 5.7e-4 
dry_mass: 34.078 # Dry rocket mass + ABS leftover: 32.708+(2.2-0.830)
dry_CM: 1.77
dry_I:
  - 39
  - 39
  - 2
propellant_mass: 10.65 #4.65
propellant_CM: 2.5
Isp: 1.0e+5 #140.5
maxThrust:
  - 50
  - 50
  - 2500
minThrust: 
  - -50
  - -50
  - 0
minTorque: -10
maxTorque: 10
Cd:
  - 2
  - 2
  - 0.33
throttling: False
input_delay: 34.0e-3 # Mean delay between external actions and its reception
output_delay: 1.0e-3 # Mean delay between output command and its effect
